### ISSUE TITLE
Sign up temporarily disabled

### ISSUE THREAD

**Issue by svnpenn** [root-io/vmail#30]
This message can be found at
http://vmail.me/en/registration
for about one month now. Can we get some communication for approximately how
long this is going to be down?

**Comment by root-io** [comment]
@felixphew Thanks for the tip

**Comment by svnpenn** [comment]
@root-io this service is a joke. 3 months downtime?

**Comment by root-io** [comment]
@svnpenn I can manually create you an account if you want, PM w/ Twitter

**Comment by svnpenn** [comment]
I sent you a tweet, it will not let me PM you

**Comment by felixphew** [comment]
@root-io Can I have an account too? Username felixphew, I don't care about the password.

**Comment by felixphew** [comment]
@root-io Also, you can delete `wusm@vmail.me`, I created it but I don't need it any more.

**Comment by TuxLyn** [comment]
Is there any plans on opening it at least in 2015 some time ?

**Comment by root-io** [comment]
@felixphew Yes, send us a tweet and we'll follow you to allow DM with Twitter for sending you the password. You can suspend your account here: https://www.vmail.me/en/user/account/

**Comment by root-io** [comment]
#33

**Comment by root-io** [comment]
issue #33

**Comment by TuxLyn** [comment]
Sending PM through Twitter is not possible if you're not following me. I've tried.

**Comment by root-io** [comment]
@TuxLyn Yep, just send us a tweet to know who follow

**Comment by root-io** [comment]
We've put postfwd in prod, let's see what will happen

**Comment by TuxLyn** [comment]
> We've put postfwd in prod, let's see what will happen ???
