### ISSUE TITLE
Invite System Request

### ISSUE THREAD

**Issue by TuxLyn** [root-io/vmail#33]
It would be great if you had some sort of invite system working. So that any people who already have accounts could invite there friends or family to register as well. Its especially useful if you don't have your email service open to general public all the time. Also some sort of dedicated email request form would be great. Very good email service, its said that its not open more often. Hopefually you can figure out all the challenges with spam that you have. Thank you and have a good 2015 year.

**Comment by root-io** [comment]
Happy new year! We are discussing about the idea of billing the service, today, we offer a free service, with no advertising, paying for server, domain name and SSL certificate.
We are hosted by a cheap french hoster, which apparently have a bad email reputation with his network and we don't pay to have a professional support, if there is a hardware problem with the server, we are offline for days (already happened in the past).
People mess with our service creating many email accounts and send a lot of spam, our hoster send us abuse messages telling us to fix the spam issues, we have to manually detect and ban incriminated accounts, it takes a lot of time.
We thought about a one time payment, like you pay to create your email (using bitcoin, paypal or whatever). If many people enjoying the service, we have a lot of idea to improve the service, but it will cost money.

**Comment by TuxLyn** [comment]
Doing only paid emails would be bad. Cuz I for one would no use it =) But if you decide to go that route at least please allow the existing accounts to be free still. Also, one or two accounts per IP address perhaps. Thank You!

**Comment by root-io** [comment]
Don't worry, accounts already created for free will stay free
