### ISSUE TITLE
User-Agent and IP Address in Emails

### ISSUE THREAD

**Issue by TuxLyn** [root-io/vmail#34]
It would be more secure to monitor this things internally to blog spam for example and not include with every email you send. So please remove "User-Agent" and "IP Address" from senders emails. From what I can see you already removed the IP Address I think. But removing "User-Agent" would be a big plus too.

**Comment by root-io** [comment]
Thanks for your suggestion, we already remove the IP address and User-Agent.

**Comment by TuxLyn** [comment]
Still see the User-Agent.

**Comment by root-io** [comment]
Could you send us a copy of the source message where the User-Agent is present: support [at] vmail.me ?

**Comment by TuxLyn** [comment]
You're right, I no longer see it. Thanks.
