### ISSUE TITLE
Fix Roundcube logout

### ISSUE THREAD

**Issue by ghost** [root-io/vmail#35]
When logging in using website, I get this "500 Internal Server Error" Then when going to main website it shows that I'm logged in but I can't access RoundCube. But IMAP works ok.

**Comment by root-io** [comment]
This error is due to the latest release of Roundcube which broke our login.
You just have to use your email address as the username when the RC login window appear.

**Comment by TuxLyn** [comment]
Yeah worked. Thanks :)

**Comment by root-io** [comment]
I think, we should let this ticket open until this issue is fixed
