### ISSUE TITLE
Vmail skin for roundcube

### ISSUE THREAD

**Issue by evertton** [root-io/vmail#45]
You need to develop a theme for the roundcube in order to make transparent their integration into vmail. And let the vmail even more attractive! :wink:

You are already working on it?

**Comment by root-io** [comment]
I was waiting for Mailpile to replace Roundcube.
The default themes are not responsive, but the Roundcube team is working on it: http://trac.roundcube.net/roadmap

**Comment by evertton** [comment]
Oh, very good... I'm watching the changes. 
I will help if I can. :smile:
