### ISSUE TITLE
Can't send mail to gmail

### ISSUE THREAD

**Issue by cm-mc** [root-io/vmail#46]
Erro de Servidor: 454
Resposta do Servidor: 454 4.7.1 <*@gmail.com>: Relay access denied
Servidor: 'vmail.me'
ID de Erro do Windows Live Mail: 0x800CCC79
Protocolo: SMTP
Porta: 465
Secure(SSL): Sim

**Comment by cm-mc** [comment]
Hello?! Anyone here?

**Comment by N-siege** [comment]
Tem certeza?

Eu enviei uma mensagem para um email do Gmail recentemente, ainda não obtive respostas. No entanto, não recebi o Erro de Servidor relatado por você. Ao invés disso, recebi uma notificação de que a mensagem foi enviada com sucesso.

Atualizarei esta mensagem futuramente para prover mais informações se eu encontrar algo.

Abraços.

-----------------------------------------------------------------------------------------------


Are you sure?

I sent a message to an email from Gmail recently, I have not got answers. However, I did not receive the Server Error reported by you. Instead, I received a notification that the message was successfully sent.

I will update this message in the future to provide more information if I find something.

Hugs.

**Comment by cm-mc** [comment]
Webmail works fine, the problem happens with email clients. I'm using settings from here:
https://www.vmail.me/en/user/expert

**Comment by cm-mc** [comment]
Still fails. Seems like the problem is with smtp only, since webmail is working fine.

"Não foi possível enviar a mensagem. A definição do seu servidor [SMTP] de envio de correio eletrónico pode ter de ser configurado. Para localizar as definições de servidor para '*@gmail.com', contacte o seu fornecedor de serviços de correio eletrónico.

Assunto 'teste'
Erro de Servidor: 454
Resposta do Servidor: 454 4.7.1 <*@gmail.com>: Relay access denied
Servidor: 'vmail.me'
ID de Erro do Windows Live Mail: 0x800CCC79
Protocolo: SMTP
Porta: 465
Secure(SSL): Sim"

**Comment by cm-mc** [comment]
Not just with gmail:

"Não foi possível enviar a mensagem. A definição do seu servidor [SMTP] de envio de correio eletrónico pode ter de ser configurado. Para localizar as definições de servidor para 'sales@prototype.pt', contacte o seu fornecedor de serviços de correio eletrónico.

Assunto 'Re: Caixa de direcção zs44/30'
Erro de Servidor: 454
Resposta do Servidor: 454 4.7.1 <sales@prototype.pt>: Relay access denied
Servidor: 'vmail.me'
ID de Erro do Windows Live Mail: 0x800CCC79
Protocolo: SMTP
Porta: 465
Secure(SSL): Sim"
