### ISSUE TITLE
can't delete any email... when you try to delete it gives the following error

### ISSUE THREAD

**Issue by outstanding-username** [root-io/vmail#47]
Server Error: UID MOVE: Mailbox doesn't exist: INBOX.Trash

**Comment by wetux** [comment]
+1 I have the same issue when trying to use web client.

**Comment by dxcs** [comment]
Same here

**Comment by dxcs** [comment]
I found a solution, try this guys : 
go in the settings to the left corner (where are the send an inboxes),
manage the folder and in the folder tab create a folder named "Trash" refresh and you should be able to delete your mails.
works for me.

**Comment by wetux** [comment]
@dxcs, I can confirm this works. Here is step by step instructions with screenshots.

### vMail Trash Workaround
---

This is how it looks before you create trash folder.
![Looks Before] (http://i.imgur.com/4KJ2scH.png)

Click on small gear icon and select "Manage folders".
![Manage Folders] (http://i.imgur.com/qsMNpLm.jpg)

Ones you see something like this, type "Trash" in "Folder name" and click Save button.
![Create Folder] (http://i.imgur.com/LdhXaEV.png)

Now you should have something like this.
![Folders View] (http://i.imgur.com/AlfZqsZ.png)

This is how it should look ones you're done.
![Looks After] (http://i.imgur.com/QNHQHQe.png)

Now you can delete any email without errors.

To empty your trash folder, select "Trash" folder then click on gear icon and select "Empty" then ones confirmation pop-up appears click on "OK" button.
![Empty Trash] (http://i.imgur.com/EMmzIqe.jpg)

Thanks **dxcs** for this workaround.

**Comment by dxcs** [comment]
You are welcome it's better with those screenshots, i didn't have time (or motivation) to do it. :)

**Comment by root-io** [comment]
Thanks :+1:
