### ISSUE TITLE
Smtp Problem (external email client)

### ISSUE THREAD

**Issue by gabrielfedel** [root-io/vmail#51]
Hello,

i'm can't send email from a external email client (thunderbird)
I receive this message when i try:

Um erro (SMTP) ocorreu ao enviar mensagens.
Resposta do servidor: “5.7.1 <DATA>: Data command rejected: Blocked - contact postmaster@vmail.me for help - Suspicious HELO [[192.168.1.4]] and missing reverse DNS [177.133.180.68]”.

**Comment by jpmorg** [comment]
Hi,

I have the same exact issue. I also use Thunderbird.

Alert

An Outgoing server (SMTP) error occurred while sending mail. The server responded:  5.7.1 <DATA>: Data command rejected: Blocked - contact postmaster@vmail.me for help - Suspicious HELO [...] and missing reverse DNS [...].

**Comment by igel-kun** [comment]
Sorry for the necromancy, but I have the same problem. It seems to be related to ```postfwd```...
