### ISSUE TITLE
Asked for credentials twice to login

### ISSUE THREAD

**Issue by cm-mc** [root-io/vmail#56]
When I log into my account, all I get is another prompt labeled roundcube asking me for my credentials again, and if I don't type them I won't be able to access the account.

**Comment by cm-mc** [comment]
Seems to be fixed now.

**Comment by root-io** [comment]
@cm-mc Thank you for reporting back :cookie:

**Comment by cm-mc** [comment]
Just got an error page after log in, asking to contact support. When I click the 'go to homepage' button, I get the same roundcube login prompt again. When I try to login there, it says connection to imap server failed. If I try to logout my account I get the error page again.
