### ISSUE TITLE
Not sending password reset email

### ISSUE THREAD

**Issue by fsir** [root-io/vmail#59]
I entered a Rescue email. Your system confirmed with "Password reset's instructions sent!"

I go to my email. No password reset email. Not in the inbox, not in the spam folder or any other folder. I performed a password request multiple times today and yesterday.

I need to get into my vmail to activate a freedompop account I just created for a $100+ cell phone I just purchased from them. Otherwise, they're going to give me a hard time, who knows, I may even have to send the phone back.

**Comment by minermoder27** [comment]
Exactly the same problem - request a password reset (to a google mail account, is this the cause?) and no message has been received.
