### ISSUE TITLE
Gateway timeout/page not found on login

### ISSUE THREAD

**Issue by cm-mc** [root-io/vmail#65]
Can't login to webmail

**Comment by mals123** [comment]
me too. can't access webmail / smtp server since more then 24 hours, returns always a 504 gateway timeout. Please fix this vmail, thanks!

**Comment by root-io** [comment]
Hey, thanks for alerting me about this, is it okay now ?

**Comment by mals123** [comment]
Working again, thanks for the fast support! :)

**Comment by cm-mc** [comment]
Yes, working again, thanks!
