### ISSUE TITLE
Account disabled

### ISSUE THREAD

**Issue by brokengillou** [root-io/vmail#72]
```
      Hi,
```

Trying to login i get error message: "User account is disabled."
But trying to change password i get no mail but rescue page says so: "Instructions de réinitialisation de mot de passe envoyés!"
What i'm supposed to do?
Could you help me?
TIA
Gilles

**Comment by root-io** [comment]
Hey, can you give me your username there support [at] vmail.me I'll see what I can do

**Comment by brokengillou** [comment]
domain is gone ...
