### ISSUE TITLE
Why does Vmail require 'window.name' function, to list emails?

### ISSUE THREAD

**Issue by cm-mc** [root-io/vmail#74]
Issue #73 below was caused by setting 'Protect `window.name`' option on in Random Agent Spoofer ff addon; if I disable it, then emails are properly listed again.
So is this function really required for Vmail proper operation? Because I've never faced this need anywhere else before.

**Comment by root-io** [comment]
You can ask about the issue you have with Random Agent Spoofer here: 
https://github.com/dillbyrne/random-agent-spoofer
or with the Roundcube webmail team
https://github.com/roundcube/roundcubemail
I think they'll have a better answer ;)

**Comment by cm-mc** [comment]
thx.
