### ISSUE TITLE
interface bug

### ISSUE THREAD

**Issue by cm-mc** [root-io/vmail#75]
top of page is hidden by the top bar:
https://sli.mg/EC35XO

**Comment by root-io** [comment]
Just made a fix, is it better ?

**Comment by cm-mc** [comment]
Yep, it's fixed now, thanks.

**Comment by cm-mc** [comment]
Hi, again, similar problem: [https://s4.postimg.org/40ozvb55p/rea_de_Transfer_ncia01.jpg](url)
