### ISSUE TITLE
Vmail down

### ISSUE THREAD

**Issue by vmailuser** [root-io/vmail#77]
Login errors, and when you can log in, nothing is working. Just database errors indicating server access fails.  This has been going on for the past few days now. Is anyone going to look at fixing this? Hard to consider this email provider for anything serious with the lack of support.

**Comment by vmailuser** [comment]
When you can log in, any time you try to read an email you get

Connection to storage server failed.
Server Error: Could not connect to ssl://vmail.me:993: php_network_getaddresses: getaddrinfo failed: No address associated with hostname

**Comment by root-io** [comment]
Are you still experiencing that issue ?

**Comment by vmailuser** [comment]
Seems fixed for now

**Comment by vmailuser** [comment]
Looks like the system is down again, unable to log in.

**Comment by vmailuser** [comment]
Are you aware that vmail isn't working again? You can't log in anymore.

**Comment by vmailuser** [comment]
Still unable to log in this morning. Just discards my user name and
password and goes to the roundcube login screen, but I can't log in from
that one either.  From the roundcube login screen, it tries loading for a
long time, then says "Connection to storage server failed" momentarily.

**Comment by vmailuser** [comment]
Looks like vmail.me is down again.

**Comment by vmailuser** [comment]
Vmail is down again.

**Comment by vmailuser** [comment]
Vmail is down. Getting 504 Gateway timeout.

**Comment by vmailuser** [comment]
Can't login today, nothing happens when you click on the Login button.

**Comment by vmailuser** [comment]
Lots of vmail problems today with logging in, reading and sending messages,
database errors, etc.
