### ISSUE TITLE
Can't send or receive email since 2017/04/23

### ISSUE THREAD

**Issue by nkestrel** [root-io/vmail#79]
Error sending email:

    An Outgoing server (SMTP) error occurred while sending mail. 
    The server responded:  4.3.5 <DATA>: Data command rejected: Server configuration problem.

Mail sent to account seems to be sent successfully but does not appear in inbox.

**Comment by menzel** [comment]
Same here

**Comment by root-io** [comment]
Problem found, seems to be fixed now, sorry for that!
