### ISSUE TITLE
504 Gateway timeouts

### ISSUE THREAD

**Issue by cm-mc** [root-io/vmail#80]
Attempts to login either flatly timeout or lead to roundcube login prompt at https://www.vmail.me/en/user/webmail/, which also fails and eventually times out as well. POP3 connections also fail.

**Comment by minetttc** [comment]
Same problem here too

**Comment by rccc** [comment]
Same problem here, "Connection to storage server failed". Is this service definitively down ?

**Comment by cm-mc** [comment]
Seems fixed, both webmail and pop3 working now.

**Comment by root-io** [comment]
Duplicate #79
