### ISSUE TITLE
Connection to storage server failed

### ISSUE THREAD

**Issue by gggeeee** [root-io/vmail#81]
![ss 2017-04-26 at 12 44 09](https://cloud.githubusercontent.com/assets/28068711/25456488/dc81bfe2-2a87-11e7-83eb-bdad85116807.jpg)
Yeah I'm not sure what's wrong but I haven't been able to access my email for ~ the past 3 days
I can't find anything on your social media accounts acknowledging this but I noticed a few others on here complaining of similar problems

**Comment by root-io** [comment]
Duplicate #79
