### ISSUE TITLE
Mail delivery latency of ~48 hours since 2017-09-12

### ISSUE THREAD

**Issue by nkestrel** [root-io/vmail#87]
Messages are often taking 48 hours to be delivered for the past few days and arrive out of order despite no increase in frequency of messages received that could potentially explain delivery being throttled.

**Comment by xjz3** [comment]
Experiencing same problem; can't receive emails via my email client and I can't log into the vmail website.

**Comment by root-io** [comment]
Thanks, I'm working on a fix.

**Comment by nkestrel** [comment]
Seems to be flowing quickly now, thanks!

**Comment by root-io** [comment]
Fixed, it was due to some spammers not being catched by the filter which limit the amount of messages per day.
