### ISSUE TITLE
Can't connect to website vmail.me

### ISSUE THREAD

**Issue by WagnerGMD** [root-io/vmail#94]
```
Connection to storage server failed.
Then we can't read the mail (etc).
Unless it isn't the right adress : https://www.vmail.me/fr/login ?
```
Hello,

apparently the trouble is back today. As you can see, it's seem to be the same message and trouble (as there [n°81](https://github.com/root-io/vmail/issues/81) or  [n°79](https://github.com/root-io/vmail/issues/79) or [n°77](https://github.com/root-io/vmail/issues/77)).

I didn't find a page contact so I will assume I need to open one new issue (at least 6 months have past).
Kind regards.

**30 December :**
The message has change because now it's :
`Too many failed login attempts. Try again later.`

**Comment by happysmash27** [comment]
Screenshot of the error in browser: 
![Connection to storage server failed](https://happysmash27.me/Upload/Screenshots/2018-01-01-145328_2560x1024_scrot.png)

**Comment by happysmash27** [comment]
For me it's still the same: ![Connection to storage server failed](https://happysmash27.me/Upload/Screenshots/2018-01-01-145328_2560x1024_scrot.png)

**Comment by WagnerGMD** [comment]
In fact, the message remain the same (as the first one). Don't try to connect again... Because there is something wrong (yes it was **my second attempts**).

To resume, I had try again today and no it doesn't work.
  
Finally [one article](https://github.com/root-io/vmail/issues/96) was published about this situation. But don't blame me if I'm little hungry. Because for sure, you could take a little time to answer me. I dislike this kind of behavior and the absence of answer and excuse.
At least, one little good news, today I was able to connect.
