### ISSUE TITLE
The mail server is completelly unresponsive

### ISSUE THREAD

**Issue by happysmash27** [root-io/vmail#95]
My email client times out, and the webmail client can't connect either. This is a really critical issue, as there is now no way for one to access their mail...

**Comment by happysmash27** [comment]
Screenshot of the error in browser: 
![Connection to storage server failed](https://happysmash27.me/Upload/Screenshots/2018-01-01-145328_2560x1024_scrot.png)

**Comment by happysmash27** [comment]
I accidentally left that comment in another thread and just fixed it now, so that's why it's so late.

**Comment by root-io** [comment]
I made some changes, could you please tell me if it has fixed your issue ? Thanks

**Comment by happysmash27** [comment]
It works now! Thank you very much!
