### ISSUE TITLE
Vmail Shutdown :(

### ISSUE THREAD

**Issue by root-io** [root-io/vmail#96]
:us: English version:

Vmail Shutdown :(

Unfortunately, we have some sad news. Vmail will cease operations at the end of March 2018. Our email server and all related support and services will turn off on March 31, 2018.

We know this is an inconvenience and we encourage you to switch to [ProtonMail](https://protonmail.com/) that provides similar services.

**DO NOT forget to:**
  - **Backup your emails**
  - **Update your email from your bank account, Facebook, Linkedin etc.**

**You won't be able to send or receive any email after the deadline.**

Thanks for being with us over the past seven years.

---

:fr: Version française:

Vmail Fermeture :(

Malheureusement, nous avons quelques mauvaises nouvelles. Vmail va cesser toutes activités à la fin du mois de Mars 2018. Notre serveur d'email et tous support et services associés seront arrêtés le 31 mars 2018.

Nous savons que c'est un inconvénient et nous vous encourageons à migrer chez [ProtonMail](https://protonmail.com/) qui fournissent des services similaires.

**N'OUBLIEZ PAS DE:**
  - **Sauvegardez vos emails**
  - **Mettre à jours votre email sur le compte en ligne de votre banque, Facebook, Linkedin etc.**

**Vous ne serez plus en mesure d'envoyer ni de recevoir des emails après la date limite.**

Merci d'avoir été avec nous depuis ces sept dernières années.

**Comment by happysmash27** [comment]
Transferring everything would be a nightmare! Is there any possibility of continuing it with the community? I have my Vmail address linked to a couple hundred accounts, and have it on several old papers too which I may not be able to change...

**Comment by happysmash27** [comment]
Oh no, I just checked and my most important account at Palemoon sync doesn't even have an option to change email address :(

**Comment by happysmash27** [comment]
Seriously though, is there any way I can help? Pretty much anything would probably be easier than editing every single instance of email address I have written…

**Comment by ZNixian** [comment]
@happysmash27 I'd highly recommend just buying a domain name, then (assuming you don't want to run your own email server) pay for mail redirection on it. Won't help now, but will prevent this from ever happening in the future, particularly if you change email provider.

**Comment by happysmash27** [comment]
Seriously though, if I remember correctly, I still have a lost phone which tells people to contact me at my Vmail address if it is found. For me, Vmail going down would be a lot more than an inconvinience…

**Comment by happysmash27** [comment]
Seriously, is there any way I can help continue the project? I keep finding websites which don't let me change my email constantly, and my text file for which sites to change is around 227 lines long...

**Comment by michelet93** [comment]
This is a bad bad bad news. 
Thank's for the best email service @root-io, it's awesome.
Best wishes for everything

**Comment by msm2020** [comment]
So sad to hear that i used my vmail for a lot of services and almost my official email.. hope if there a good alternative

**Comment by cm-mc** [comment]
If you're looking for an alternative, forget Protonmail; it's free accounts don't let you use pop3/imap, or even import/export mail, only "print". And then it's all encrypted, _even if from/to plain text servers_ like vmail, which is beyond stupid.

**Comment by unendinglove** [comment]
You're right cm-mc, I checked out Protonmail too, no similarities to Vmail. Can't download your email.
So I went to Disroot (disroot.org) and I'm quite happy with their service. I've been using it for a little over a couple of months now.
I also want to thank the Vmail owners for their services all these years & for giving us enough advance notice to find an alternative and make the transition. Really appreciate it!
Sorry to see you go...  Great job, thanks again!

**Comment by cm-mc** [comment]
Thanks for the tip @unendinglove and second you too; farewell and thanks for all the fish, Vmail... too many of us broke ass gits and not enough dough, I guess...

**Comment by happysmash27** [comment]
@cm-mc: I personally would be willing to pay a LOT of money to keep Vmail online, but @root-io hasn't responded :(

**Comment by unendinglove** [comment]
@happysmash27 Maybe he didn't realize you were willing to pay a **LOT** of money to help, that's why he didn't respond...

**Comment by unendinglove** [comment]
@cm-mc You're very welcome! :)

**Comment by happysmash27** [comment]
Is there anything I can do to get you to put back on the service for just a day? Liqui has not responded to my ticket yet, and now I have thousands of dollars I cannot confirm the transaction of because my email doesn't work! Someone please help! Someone please!

**Comment by root-io** [comment]
@happysmash27 We did not close the service entirely yet, we've just disabled emails sending. Do you need the feature to confirm your transaction ?

**Comment by happysmash27** [comment]
No, I, but I get a "Bad credentials" error.

**Comment by alen-sherif** [comment]
@happysmash27
@root-io
I get a "Bad credentials" error too.

**Comment by nkestrel** [comment]
@root-io Haven't received emails since 2nd April.

**Comment by OJepez** [comment]
Hi!
What is this nonsence about shutdown  of vmail end of March?
Receiving lots of spam still today!
But maybe the first time today was not able send anything...

**Comment by maxgiaco01** [comment]
I'm really sad
I wish you all the best to all the team.
I've looked at [protonmail](https://protonmail.com/) but it's too much expensive for my customers and I moved to [servermx](https://servermx.com/)

Thanks for the service provided
Max

**Comment by happysmash27** [comment]
Microsoft is now asking for me to verify with my vmail address to log in :(
