### ISSUE TITLE
Vmail bocking confirmation emails from bitstamp.net

### ISSUE THREAD

**Issue by VmailHelp** [root-io/vmail#97]
Since email is shutting down at the end of March, I'm trying to update my email addresses with all service providers. But it seems that Vmail's spamassassin is blocking emails from bitstamp.net, so I'm unable to receive the confirmation emails to change my info.

Is there any way to fix this on your end? Otherwise I will completely loose access to that account after March 31st :(

**Comment by root-io** [comment]
Could you provide more info, how do you know it is spamassassin that blocks you from receiving your email? Did you try to wait few hours/days then try again ?

**Comment by VmailHelp** [comment]
Since there is no trace of these emails in the Junk folder, spamassasin is an assumption as roundcube doesn't have a whitelisting feature. Plus the sender already ran a variety of server forensics and found no issue on their end. Because these are automated emails, they're the kind of thing spamassain blocks if the throttle is set too aggressively.

**Comment by root-io** [comment]
Thanks for the explanation, I think we are not discarding any email based on the spamassassin's score but I'm not 100% sure and it could be that something else is blocking.
Is it possible for you shoot us your vmail username at: support [at] vmail.me so I can take a further look at it?

**Comment by root-io** [comment]
I contacted Bitstamp I'm waiting for an answer from them. I'll also plan a reboot of the server, it might solves the issue. I'll keep you guys in touch.

**Comment by VmailHelp** [comment]
Thanks! I really appreciate it!

**Comment by VmailHelp** [comment]
Any updates on this issue? I haven't heard back and I'm still not receiving these emails...

**Comment by root-io** [comment]
A reboot was done today, no news from Bitstamp, I guess I can't receive emails from them either as I contacted them with a vmail address.
