### ISSUE TITLE
Vmail is down, but I am not finished migrating my accounts

### ISSUE THREAD

**Issue by happysmash27** [root-io/vmail#98]
I have a LOT of accounts, so migrating takes a very long time. I just got to an account which needs activation from my old email to be changed though, but I can't access Vmail as the server seems to be down.

**Comment by root-io** [comment]
I don't have any issue accessing vmail. Could you be more specific, what happens exactly ?

Just don't flood the server with authentication or you'll get blocked automatically.
For example if you try to login more than 30 times in less than 10 minutes you'll get ban 1h.

To test if you're ban you can `ping vmail.me`, if you don't get any answer then there is a high chance you're on the ban list, or you have a network issue.

**Comment by happysmash27** [comment]
Daheck? It started working again, but I just realised that that's only because I turned Tor back _on_…

Now I'm not wondering why my home PC address is blocked when all of my proxies aren't…
